#!/bin/bash

if [ $# -lt 5 ];then
	echo0 1 $0" in.bed2 in.feature.sizes out.prefix factor CPU picluster|transposon|gene"
	exit 1
fi
CPU=$5
FACTOR=$4
FACTOR_PP=`awk -v factor=$FACTOR 'BEGIN{print factor*factor}'`

PATH_BED2=${3}_temp_bed2 && mkdir -p ${PATH_BED2}
PATH_LENDIS=${3}_temp_lendis && mkdir -p ${PATH_LENDIS}
PATH_PP=${3}_temp_pp && mkdir -p ${PATH_PP}
PATH_SIGNAL=${3}_temp_signal && mkdir -p ${PATH_SIGNAL}
PARA_FILE1=${3}_temp_para1
PARA_FILE2=${3}_temp_para2
PARA_FILE3=${3}_temp_para3
PARA_FILE4=${3}_temp_para4
seperate_bed2.py $1 $2 ${PATH_BED2}
for i in ${PATH_BED2}
do
	bn=`basename $i`
	n=${bn%.bed2}
	echo -e "bed2_lendis $i ${PATH_LENDIS}/${n}.lendis ${FACTOR}" >> ${PARA_FILE1}
	echo -e "bed2_pingpong -a $i -b $i > ${PATH_PP}/${n}.pp ${FACTOR_PP}" >> ${PARA_FILE2}
	echo -e "awk -v factor=$FACTOR 'BEGIN{FS=OFS=\"\\\t\"} {if(\$6==\"+\" && \$5==1){sum1+=\$4/\$5}else if(\$6==\"-\" && \$5==1){sum2+=\$4/\$5}i;if(\$6==\"+\" &&){sum3+=\$4/\$5}else{sum4+=\$4/\$5}} END{print sum1/factor,sum2/factor,sum3/factor,sum4/factor}' $i > ${PATH_SIGNAL}/${n}.rpm" >> ${PARA_FILE3}
	echo -e "awk -v 'BEGIN{FS=OFS=\"\\\t\"} {if(\$6==\"+\" && \$5==1){sum1++}else if(\$6==\"-\" && \$5==1){sum2++};if(\$6==\"+\"){sum3++}else{sum4++}} END{print sum1/factor,sum2/factor,sum3/factor,sum4/factor}' $i > ${PATH_SIGNAL}/${n}.species" >> ${PARA_FILE4}
done
ParaFly -c ${PARA_FILE1} -CPU ${CPU} && rm ${PARA_FILE1}
ParaFly -c ${PARA_FILE2} -CPU ${CPU} && rm ${PARA_FILE2}
ParaFly -c ${PARA_FILE3} -CPU ${CPU} && rm ${PARA_FILE3}
ParaFly -c ${PARA_FILE4} -CPU ${CPU} && rm ${PARA_FILE4}
for i in ${PATH_BED2}
do
	bn=`basename $i`
	n=${bn%.bed2}
	echo -en "\t${n}" >> ${3}_header1
	cut -f 2 ${PATH_LENDIS}/${n}.lendis > ${PATH_LENDIS}/${n}.sense 
	cut -f 3 ${PATH_LENDIS}/${n}.lendis > ${PATH_LENDIS}/${n}.anti 
	cut -f 2 ${PATH_PP}/${n}.pp > ${PATH_PP}/${n}.ppc 
	rd=`cat ${PATH_SIGNAL}/${n}.rpm`
	sp=`cat ${PATH_SIGNAL}/${n}.species`
	echo -e "${n}\trd\tsp" >> ${3}_body4
done
echo -e "name\tuniq_sense_reads\tuniq_antisense_reads\tall_sense_reads\tall_antisense_reads\tuniq_sense_species\tuniq_antisense_species]tall_sense_species\tall_antisense_species" > ${3}_header2
echo -e "" >> ${3}_header1
paste ${PATH_LENDIS}/*.sense > ${3}_body1 
paste ${PATH_LENDIS}/*.anti > ${3}_body2 
paste ${PATH_PP}/*.ppc > ${3}_body3 
cat ${3}_header1 ${3}_body1 > ${3}.$6.sense.lendis
cat ${3}_header1 ${3}_body2 > ${3}.$6.antisense.lendis
cat ${3}_header1 ${3}_body3 > ${3}.$6.pp
cat ${3}_header2 ${3}_body4 > ${3}.$6.summary
rm ${3}_header* ${3}_body*
rm -rf ${3}_temp*


