#!/bin/bash

#help file
if [ $# -lt 4 ];then
	echo0 1 $0" in.piRNAcluster.bed2 in.transposon.bed2 in.hairpin.bed2 in.genome.bed2 out.prefix [CPU]"
	exit 1
fi

#initialize parameters
PATH_PROG=`dirname $0`
PIRNA=$1
TRANSPOSON=$2
HAIRPIN=$3
GENOME=$4
PATH_OUT=`dirname $5`
if [ $# -gt 5 ];then
	CPU=$6
else
	CPU=1
fi

#calculate normlization factor
FACTOR=(`awk '{sum+=$4/$5} END{print sum/1000000}' $3`)

#get summary
get_bed2_summary $1 ${PATH_PROG}/annotation/dm3/piRNAcluster.sizes $5 ${FACTOR} ${CPU} picluster
get_bed2_summary $2 ${PATH_PROG}/annotation/dm3/transposon.sizes $5 ${FACTOR} ${CPU} transposon
bedtools intersect -a $4 -b ${PATH_PROG}/annotation/dm3/gene.exon.bed -wo -f 1 | awk 'BEGIN{FS=OFS="\t"} {gn=$11;if($6==$13){strand="+"}else{strand="-"};print gn,$2,$3,$4,$5,strand,$7}' > $5_temp_gene.bed2 
awk 'BEGIN{FS=OFS="\t"} {if(NR==FNR){a[$2]=$1}else{$1=a[$1];print $0}}' ${PATH_PROG}/annotation/dm3/gene.map $5_temp_gene.bed2 > $5_temp_gene.transform.bed2
get_bed2_summary $5_temp_gene.transform.bed2 ${PATH_PROG}/annotation/dm3/gene.map $5 ${FACTOR} ${CPU} gene
transform_id_to_name.R $5.gene ${PATH_PROG}/annotation/dm3/gene.map

#modify tables and plot
modify_and_plot_summary.R $5.picluster
modify_and_plot_summary.R $5.transposon
modify_and_plot_summary.R $5.gene
